name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'  # Specify the Ruby version you need

    - name: Install dependencies
      run: |
        gem install bundler -v 2.4.22
        bundle install

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Use the latest Node.js version

    - name: Install Tailwind CSS and PostCSS
      run: |
        npm install
        npm install postcss postcss-cli

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
